### ISSUE TITLE
[QuickLyric] StackOverflow on smell checks

### ISSUE THREAD

**Issue by aveuiller** [HSarah/Tandoori#5]
```
# Parsing project database to find smells
Exception in thread "main" java.lang.StackOverflowError
        at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
        at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
        at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
        at java.util.regex.Pattern$Curly.match0(Pattern.java:4279)
        at java.util.regex.Pattern$Curly.match(Pattern.java:4234)
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
        at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
        at java.util.regex.Pattern$Start.match(Pattern.java:3461)
        at java.util.regex.Matcher.search(Matcher.java:1248)
        at java.util.regex.Matcher.find(Matcher.java:664)
        at java.util.Formatter.parse(Formatter.java:2549)
        at java.util.Formatter.format(Formatter.java:2501)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.getNodeById(GraphDatabaseFacade.java:312)
        at org.neo4j.cypher.javacompat.internal.GraphDatabaseCypherService.getNodeById(GraphDatabaseCypherService.java:70)
        at org.neo4j.cypher.internal.spi.v3_1.TransactionBoundQueryContext$NodeOperations.getById(TransactionBoundQueryContext.scala:341)
        at org.neo4j.cypher.internal.spi.v3_1.TransactionBoundQueryContext$$anonfun$getNodesByLabel$1.apply(TransactionBoundQueryContext.scala:283)
        at org.neo4j.cypher.internal.spi.v3_1.TransactionBoundQueryContext$$anonfun$getNodesByLabel$1.apply(TransactionBoundQueryContext.scala:283)
        at org.neo4j.cypher.internal.compiler.v3_1.helpers.JavaConversionSupport$$anon$5.fetchNext(JavaConversionSupport.scala:60)
        at org.neo4j.cypher.internal.compiler.v3_1.helpers.JavaConversionSupport$$anon$5.fetchNext(JavaConversionSupport.scala:63)
        at org.neo4j.cypher.internal.compiler.v3_1.helpers.JavaConversionSupport$$anon$5.fetchNext(JavaConversionSupport.scala:63)
        at org.neo4j.cypher.internal.compiler.v3_1.helpers.JavaConversionSupport$$anon$5.fetchNext(JavaConversionSupport.scala:63)
       [ ...Same call until crash... ]
```

**Comment by aveuiller** [comment]
Should be fixed by increasing stack size (currently trying with 512Mo instead of 1Mo)
