### ISSUE TITLE
[afwall, openbmap, andstatus, Lightning-Browser,QuickLyric] Missing field in NOSMELL output (commit_number)

### ISSUE THREAD

**Issue by aveuiller** [HSarah/Tandoori#6]
The database may be corrupted?

Example file with Lightning:

```
commit_number,key,instance,commit_status,id
551,ce3923d336f82d8b97b8058bae37b9847904323d,-,with_dependencies,1966779
593,e9203f20b35c70cfec3557651dd787e12e1a455b,-,with_dependencies,1966779
633,f061a35472e1adcaff09fdab45d3fbde4e7e9527,-,with_dependencies,1966779
673,b619a12ae38f600b0dfb6a1b33e8a706171f0385,-,with_dependencies,1966779
713,732d30988802f1b0bdec505877764012c833eaa9,-,with_dependencies,1966779
753,6f36410e872c6aa194b33193f4445a452999a3d5,-,with_dependencies,1966779
793,ce0e02585c4f02e3607d7e76a1ab64f186f0b8cc,-,with_dependencies,1966779
833,1eeddaf502b8d5f6ef613875191ddea91cc6aa79,-,with_dependencies,1966779
873,0185b5c1ba087f4f69aeac4c3ab924707c634d22,-,with_dependencies,1966779
913,359a252f24d5d664ca83f209351eb4799a751f93,-,with_dependencies,1966779
953,486078a7d1513a11d7f3d9e31a95ed26b119657a,-,with_dependencies,1966779
993,6e940b0a1536ccbadc7f0798da306669dbb45d8c,-,with_dependencies,1966779
1033,0b2ba8fbf331b21c58ec805eca0ba2e226811fd1,-,with_dependencies,1966779
1073,8ae8f58cc6f9ba42570ff3a3dc63bad4c21661a5,-,with_dependencies,1966779
1113,f51d38598deba2d2d5bd193a77002bcd3b65ff03,-,with_dependencies,19363341
e1ffe3b7fbfffcca6c127c9e9245bb9a701d12c2,-,,1966779
e1ffe3b7fbfffcca6c127c9e9245bb9a701d12c2,-,,1966779
e1ffe3b7fbfffcca6c127c9e9245bb9a701d12c2,-,,1966779
e1ffe3b7fbfffcca6c127c9e9245bb9a701d12c2,-,,1966779
e1ffe3b7fbfffcca6c127c9e9245bb9a701d12c2,-,,1966779
[...]
e1ffe3b7fbfffcca6c127c9e9245bb9a701d12c2,-,,1966779
54115b55b021587c7fbf6c5872acdc6f23f47c16,-,,1966779
54115b55b021587c7fbf6c5872acdc6f23f47c16,-,,1966779
54115b55b021587c7fbf6c5872acdc6f23f47c16,-,,1966779
54115b55b021587c7fbf6c5872acdc6f23f47c16,-,,1966779
54115b55b021587c7fbf6c5872acdc6f23f47c16,-,,1966779
54115b55b021587c7fbf6c5872acdc6f23f47c16,-,,1966779
54115b55b021587c7fbf6c5872acdc6f23f47c16,-,,1966779
54115b55b021587c7fbf6c5872acdc6f23f47c16,-,,1966779

```

```
# Computing metrics for project openbmap - wish7code/openbmap
Using appDB /run/media/antoine/Maxtor/tandoori-metrics/databases/openbmap
# Parsing project database to find smells
/run/media/antoine/Maxtor/tandoori-metrics
# Retrieving project developers profiles on github
/run/media/antoine/Maxtor/tandoori-metrics
# Merging developers with smells files
# Generating global metrics file
2017-07-26 19:46:44 INFO   SmellsProcessor:49 - Processing smell file: 2017_7_26_19_46_UIO.csv
2017-07-26 19:46:44 INFO   SmellProcessor:38 - Processing smell type: UIO
2017-07-26 19:46:44 INFO   SmellsProcessor:49 - Processing smell file: 2017_7_26_19_46_UHA.csv
2017-07-26 19:46:44 INFO   SmellProcessor:38 - Processing smell type: UHA
2017-07-26 19:46:44 INFO   SmellsProcessor:49 - Processing smell file: 2017_7_26_19_46_UCS.csv
2017-07-26 19:46:44 INFO   SmellProcessor:38 - Processing smell type: UCS
2017-07-26 19:46:44 INFO   SmellsProcessor:49 - Processing smell file: 2017_7_26_19_46_NOSMELL.csv
2017-07-26 19:46:44 INFO   SmellProcessor:38 - Processing smell type: NOSMELL
2017-07-26 19:46:44 WARN   InputSmell:44 - Unable to parse smell input: cc5e5da1a991d25496121be7c1c5d2c53450642e,-,,8270020
Exception in thread "main" java.lang.NumberFormatException: For input string: "cc5e5da1a991d25496121be7c1c5d2c53450642e"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.tandoori.metrics.calculator.processing.InputSmell.fromLine(InputSmell.java:46)
        at org.tandoori.metrics.calculator.processing.SmellProcessor.process(SmellProcessor.java:50)
        at org.tandoori.metrics.calculator.processing.SmellsProcessor.process(SmellsProcessor.java:51)
        at org.tandoori.metrics.calculator.SmellsCalculator.generate
```

**Comment by aveuiller** [comment]
Database has been reprocessed and is no error anymore.
