### ISSUE TITLE
[CampFahrplan,Lightning-Browser,notepad] File error on Neo4j request

### ISSUE THREAD

**Issue by aveuiller** [HSarah/Tandoori#7]
The database may be corrupted or the disk access problematic, I will investigate.
```
# Parsing project database to find smells
java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /run/media/antoine/Maxtor/tandoori-metrics/databases/CampFahrplan/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:193)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:101)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory.lambda$createDatabaseCreator$0(GraphDatabaseFactory.java:89)
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:183)
        at neo4j.DatabaseManager.start(DatabaseManager.java:23)
        at neo4j.QueryEngine.<init>(QueryEngine.java:60)
        at analyzer.Main.queryMode(Main.java:129)
        at analyzer.Main.main(Main.java:54)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine@7d1a82a6' failed to initialize. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:415)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:517)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
        ... 8 more
Caused by: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=5ygkd1quj3t1ifoz52wtsm3hb, got=72bl4zkn2r1wc7pr0u6057uil (resource=BufferedChecksumIndexInput(MMapIndexInput(path="/run/media/antoine/Maxtor/tandoori-metrics/databases/CampFahrplan/databases/graph.db/schema/label/lucene/labelStore/1/_g9.si")))
        at org.apache.lucene.codecs.CodecUtil.checkIndexHeaderID(CodecUtil.java:266)
        at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:256)
        at org.apache.lucene.codecs.lucene50.Lucene50SegmentInfoFormat.read(Lucene50SegmentInfoFormat.java:86)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:362)
        at org.apache.lucene.index.IndexFileDeleter.<init>(IndexFileDeleter.java:171)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:949)
        at org.neo4j.kernel.api.impl.index.partition.WritableIndexPartition.<init>(WritableIndexPartition.java:48)
        at org.neo4j.kernel.api.impl.index.partition.WritableIndexPartitionFactory.createPartition(WritableIndexPartitionFactory.java:45)
        at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.open(AbstractLuceneIndex.java:98)
        at org.neo4j.kernel.api.impl.index.WritableAbstractDatabaseIndex.open(WritableAbstractDatabaseIndex.java:64)
        at org.neo4j.kernel.api.impl.labelscan.LuceneLabelScanStore.init(LuceneLabelScanStore.java:159)
        at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.init(RecordStorageEngine.java:419)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:405)
        ... 17 more
        Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (e6d853f2). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(MMapIndexInput(path="/run/media/antoine/Maxtor/tandoori-metrics/databases/CampFahrplan/databases/graph.db/schema/label/lucene/labelStore/1/_g9.si")))
                at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:379)
                at org.apache.lucene.codecs.lucene50.Lucene50SegmentInfoFormat.read(Lucene50SegmentInfoFormat.java:117)
                ... 27 more
/run/media/antoine/Maxtor/tandoori-metrics

```

**Comment by aveuiller** [comment]
Most likely due to corrupted database indeed.
