### ISSUE TITLE
[orWall] Some analyzed commits are absent from smell files

### ISSUE THREAD

**Issue by aveuiller** [HSarah/Tandoori#8]
When smells are processed in https://github.com/aveuiller/MetricsCalculator for the project `orWall`, we only have an output of __582__ commits out of __595__ analyzed ones.

To be more precise, the missing commit numbers are:
161,162,163,165,166,167,178,183,184,260,310,454,455
i.e.
https://github.com/EthACKdotOrg/orWall/commit/2c5b31de8e0c497e5697354c0425681c68e59362
https://github.com/EthACKdotOrg/orWall/commit/
https://github.com/EthACKdotOrg/orWall/commit/

**Comment by aveuiller** [comment]
The project has been processed two times to eliminate any case of database corruption

**Comment by aveuiller** [comment]
After verification, those specifics commits seems to be absent from the database.

e.g. (commit 161): 
```
I, [2017-07-20T17:50:58.960381 #39537]  INFO -- : App: orWall, commit 2c5b31de8e0c497e5697354c0425681c68e59362, DONE WITH EXCEPTION(S) RAISED BY PAPRIKA
D, [2017-07-20T17:50:58.960562 #39537] DEBUG -- : err: spoon.SpoonException: Printing of spoon.support.reflect.code.CtFieldReadImpl on path 
        CtPackageImpl:org
        CtPackageImpl:ethack
        CtPackageImpl:orwall
        CtClassImpl:PreferencesActivity
        CtClassImpl:NetworkPrefs
        CtFieldImpl:listener
        CtNewClassImpl
        CtClassImpl:1
        CtMethodImpl:onSharedPreferenceChanged
        CtBlockImpl
        CtIfImpl
        CtBlockImpl
        CtInvocationImpl
        CtFieldReadImpl:PARAM_ACTIVATE
at position (/home/sarra/orWall/app/src/main/java/org/ethack/orwall/PreferencesActivity.java:126) failed
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:307)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtInvocation(DefaultJavaPrettyPrinter.java:1162)
        at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:57)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:298)
        at spoon.reflect.visitor.printer.ElementPrinterHelper.writeStatement(ElementPrinterHelper.java:139)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtBlock(DefaultJavaPrettyPrinter.java:476)
        at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:49)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:298)
        at spoon.reflect.visitor.printer.ElementPrinterHelper.writeStatement(ElementPrinterHelper.java:139)
        at spoon.reflect.visitor.printer.ElementPrinterHelper.writeIfOrLoopBlock(ElementPrinterHelper.java:366)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtIf(DefaultJavaPrettyPrinter.java:1076)
        at spoon.support.reflect.code.CtIfImpl.accept(CtIfImpl.java:46)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:298)
        at spoon.reflect.visitor.printer.ElementPrinterHelper.writeStatement(ElementPrinterHelper.java:139)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtBlock(DefaultJavaPrettyPrinter.java:476)
        at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:49)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:298)
        at spoon.support.reflect.declaration.CtElementImpl.toString(CtElementImpl.java:249)
        at analyzer.ExecutableProcessor.countEffectiveCodeLines(ExecutableProcessor.java:57)
        at analyzer.ExecutableProcessor.process(ExecutableProcessor.java:38)
        at analyzer.ClassProcessor.processMethods(ClassProcessor.java:63)
        at analyzer.ClassProcessor.process(ClassProcessor.java:50)
        at analyzer.ClassProcessor.process(ClassProcessor.java:23)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:92)
        at spoon.reflect.visitor.CtScanner.visitCtNewClass(CtScanner.java:581)
        at spoon.support.reflect.code.CtNewClassImpl.accept(CtNewClassImpl.java:35)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
        at spoon.reflect.visitor.CtScanner.visitCtField(CtScanner.java:387)
        at spoon.support.reflect.declaration.CtFieldImpl.accept(CtFieldImpl.java:68)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
        at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:308)
        at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:69)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
        at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:308)
        at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:69)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:629)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:57)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:628)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:57)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
        at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:628)
        at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:57)
        at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:150)
        at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
        at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:119)
        at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:131)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.process(JDTBasedSpoonCompiler.java:184)
        at spoon.Launcher.process(Launcher.java:707)
        at analyzer.MainProcessor.process(MainProcessor.java:57)
        at analyzer.Main.runAnalysis(Main.java:105)
        at analyzer.Main.main(Main.java:50)
Caused by: java.lang.NullPointerException
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.printCtFieldAccess(DefaultJavaPrettyPrinter.java:775)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtFieldRead(DefaultJavaPrettyPrinter.java:747)
        at spoon.support.reflect.code.CtFieldReadImpl.accept(CtFieldReadImpl.java:27)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:298)
        ... 68 more
```
